name: Setup repository
on:
  create
jobs:
  setup:
    name: Reinitialize repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check if this repo is a template repo then exit
        shell: bash
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update project name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "angular-template"
          replace: ${{ github.event.repository.name }}
          regex: false

      - name: Remove this workflow file
        shell: bash
        run: |
          rm ./.github/workflows/setup-repository.yaml

      - name: Reinitialize git repository
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git checkout --orphan temp-branch && \
          git add . && \
          git commit -m 'Initial commit' && \
          git push origin temp-branch:main -f
